version: "2"
services:
  postman_checks:
      container_name: Api_Tests_npm_docker_latest1
      image: subrat1982/newman-postman:latest
      command:
        run Corporate-Sending-Final-Testcases-DEV.postman_collection.json
        -e  environments/Corporate-Sending.postman_environment.json
        -r  html,htmlextra,cli
        --reporter-htmlextra-title  Api_Tests_Dev
        --reporter-htmlextra-export reports/Api_Tests_Dev.html
        --reporter-html-export reports/Api_Tests_Dev.html
        --reporter-html-template reports/templates/customTemplate.hbs
      volumes:
        - ./src:/etc/newman
